### ISSUE TITLE
Token HUD don't work

### ISSUE THREAD

**Issue by Eskazen** [reonZ/pf2e-hud#10]
First of all good job with such a wonderful module.
I have run into an issue I'm using Foundry v12.330 and pf 6.1.3. 
I don't know if it is just me but token HUD doesn't show up no matter what, 
I even created a new world and launched only pf2e HUD and still nothing combat tracker, persistent HUD etc. works.

**Comment by reonZ** [comment]
https://github.com/reonZ/pf2e-hud/wiki/Persistent-HUD#auto-set-actor---disabled

**Comment by Eskazen** [comment]
That was it! Thank you reonZ. I looked through a wiki before but I didn't notice the note xD

**Comment by reonZ** [comment]
It is also pointed out in the setting itself.
