### ISSUE TITLE
[Feature request] [Persistent HUD] Allow Effect shortcuts

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-hud#13]
Use case:  I have a Swashbuckler who frequently needs to toggle the Panache effect on or off (adding it or removing it), about once per turn.
- I can't drag the Effect (from compendium/directory/actor) to the shortcuts -- warning says "You cannot create shortcuts of this type"
- There isn't a Panache toggle in the Actions sidebar/popup, because it's an effect, not a toggle
- I can put the entire Panache feat as a shortcut, but clicking it just shows the description
- I can create a macro by dragging the effect to my macro hotbar, and it works perfectly -- except it's in the hotbar, not in the token's own shortcuts
- I can put that macro in the Extra sidebar, and it works perfectly -- but it requires an extra click and I don't want that extra click (I'm a spoiled child)

So... my request is that dragging an Effect to the shortcuts will work, and clicking on it will apply or unapply the effect.

For bonus points, make that effect shortcut tinted in grayscale when it's inactive, and go full color when it's active.  Just like the weapon stowed/drawn vfx.

**Comment by reonZ** [comment]
I tend to avoid doing something that is already readily available, and system effect macros are working fine and are just there, inside the HUD.

Now on to a more technical and design reason, every shortcut is something dragged from the sidebars, effects wouldn't be.

As to your last part, that would be good if all effects in the system are on/off toggles, but that isn't the case, you can have multiple instances of certain effects.
