### ISSUE TITLE
Support for fast switching between several characters owned by the same player

### ISSUE THREAD

**Issue by apoapostolov** [reonZ/pf2e-hud#15]
In my games, players regularly bring over secondary characters or take over characters from other players who are missing. While PF2 HUD is a godsent gift to manage your character even when the Party Clown Car is all that is on the map, it still requires targets to switch between characters. I would like to ask for a method to assign mutliple fast-swap characters that players can swap very quickly.

Fast swap micro-portraits shown in one of the corners of the main portrait. Can be limited to acceptable limit (up to 3..5) Click on the micro-portrait to swap current owned actor with the other owned actor. Very fast to manage. Right click on a microportrait to empty it

![image](https://github.com/user-attachments/assets/eda03657-076b-4769-9ca2-d6d868cf4c0c)

Keyboard UX:
- shift-leftclick on linked owned target to add to your Party HUD as a secondary option. It adds the option to one of the free micro-portraits (see below) or shows a warning limit of maximum fast-swap characters have been reached.

**Comment by reonZ** [comment]
This is something that should be handled with a macro in your world, you can already use tab to switch between tokens on foundry, and wanting to quick swap between actors that aren't on the board is  too much of an exception.

**Comment by apoapostolov** [comment]
That's okay, please consider at least adding a macro compendium to the mod with the macro that was made by @shemetz

```
const myActorsUuids = [
  "Actor.i7ZLWbui3oivaFu5",
  "Actor.uLM0pWloSbCRFifh",
  "Actor.0PdNYWTmyNzB6mpz"
]
const currActorUuid = game.hud.persistent.actor?.uuid
const currActorIdx = myActorsUuids.indexOf(currActorUuid)
const nextActorIdx = (currActorIdx + 1) % myActorsUuids.length
const nextActorId = myActorsUuids[nextActorIdx]
const nextActor = fromUuidSync(nextActorId)
game.hud.persistent.setActor(nextActor)
```

Hopefully he will be okay to include it so everyone can use it for such cases.

**Comment by reonZ** [comment]
I am not adding any compendium to the module, especially not for one macro.

**Comment by shemetz** [comment]
I agree, I think if this module ends up getting a lot of user macros (which isn't certain) they would be better collected in e.g. a github wiki page, with clear instructions on what they do and how to edit them
