### ISSUE TITLE
Option to customize behavior on doubleclick on the large portrait in Persistent HUD

### ISSUE THREAD

**Issue by apoapostolov** [reonZ/pf2e-hud#18]
Currently clicking on it causes it to open the Edit Avatar.
It would be very useful if this was customizable:
- Open Character Sheet
- Center on Selected Actor
- Edit Avatar (on by default since people expect the behavior)

**Comment by reonZ** [comment]
You can already open the actor sheet with the menu on the left

**Comment by reonZ** [comment]
Also, the persistent HUD is related to an actor, it doesn't care about tokens, so a "center to token" feature wouldn't make sense.
