### ISSUE TITLE
Skill actions and MAP

### ISSUE THREAD

**Issue by lholden** [reonZ/pf2e-hud#2]
Great addon!

I'd really love if I could drag a skill action like Trip to the mods quick actions from the skills menu and still have access to the MAP options like I would if I dragged an attack. I know I can drag one of each map, but it would be cool if this could handle it more like strikes :D.

**Comment by reonZ** [comment]
Shortcuts are meant to be "click and go" and this would require the use of an extra popup of sort to let you select the MAP.

**Comment by lholden** [comment]
Couldn't implement it the same way the weapons work with the mouse over MAP options? 

Anyhow, no worries :)

**Comment by reonZ** [comment]
Not really, the way i implemented the shortcut relies on the fact that only strikes/blasts are taking a full slot, this is a part of the code that is rigid.
