### ISSUE TITLE
Few Requests

### ISSUE THREAD

**Issue by xKillerbees** [reonZ/pf2e-hud#21]
Would put in a label for feature request but none available. 

![image](https://github.com/user-attachments/assets/7fecb02a-18a9-4302-86e7-e54e443879b7)
vs
![image](https://github.com/user-attachments/assets/07c54a4c-4ab8-4491-a39a-9bb312692f9f)

Any chance we can get the actions tab to show pictures to help with the visual clutter of some of the bigger menus. In the action HUD module I am showing the example of how it's structured that the group thinks it's easier to see. I want to swap to the pf2e hud long term. 

-----------------------------------------

Second idea is to allow an option to swap the skills menu with the BAM from pf2e workbench. The group has gotten to used to the visual of that macro and the hide if untrained in it works while in pf2e hud it doesn't seem to hide skills that are untrained. 

![image](https://github.com/user-attachments/assets/c78fafc5-4825-4fea-8a3b-9f67f75e0dee)
![image](https://github.com/user-attachments/assets/4ab473e6-9e51-4efb-ab52-e33812d8d3cb)

-----------------------------------------------------------------

![image](https://github.com/user-attachments/assets/ef8a5a6a-de78-4cb8-b5e8-4c138bd84515)
Here is an example for above where the icon colors help your vision when trying to get used to the UI to find what you want. I think this could be expanded to more color options for the persistent hud. The HP icon for example in the bottom left could be green. The Hero points could be yellow etc.

**Comment by reonZ** [comment]
1/ most actions don't have icons, also, the icon would be very small on a single line like that, but i may make the change regardless

2/ i don't support any module

3/ it hides the actions not the skills, untrained characters can still make skill checks and some actions don't require to be trained anyways
