### ISSUE TITLE
Delete Encounter from Combat Tracker

### ISSUE THREAD

**Issue by ConnorJBeck** [reonZ/pf2e-hud#26]
Hello, loving this module!

This a feature request for the ability to delete an encounter from the tracker (the "Trash Can" button in the regular combat tracker) before an encounter has started. I use this feature here and there when playing the game (e.g. if I accidentally start an encounter then my party talks their way out of it or we never end up starting for some reason), and I use it a lot when I'm testing various things between sessions. I could maybe see it going where the XP calculation icon goes when you actually start the combat?

Anyways, thanks, and no rush, just a minor convenience that would probably allow me to never use the built in tracker again :)

**Comment by reonZ** [comment]
You can just double click on the "being encounter" -> "end encounter" i suppose, this is really a fringe situation that doesn't warrant a change.
