### ISSUE TITLE
Recall Knowledge for Lores in skill sidebar

### ISSUE THREAD

**Issue by fotoply** [reonZ/pf2e-hud#27]
Lore skills currently trigger a normal roll without the action being recall knowledge, when clicking them.

It would be nice it a button similar to the variants added to `Perform` (Acting, Comedy, etc) was added to each of the Lore skills, allowing you to easily recall knowledge with a lore.

**Comment by reonZ** [comment]
There is a full recall knowledge action in the "extras" sidebar, i don't feel like investing more time on something that is already entirely covered.
