### ISSUE TITLE
Allies health is visible in combat tracker when "Party Alliance as Observed" is turned off

### ISSUE THREAD

**Issue by ConnorJBeck** [reonZ/pf2e-hud#28]
Sorry if I'm just missing something, I've been hacking away at this for a little while and I can't figure out why it's happening. 

My players are able to see the HP of their fellow party members in in the combat tracker, even when I have "Party Alliance as Observed" disabled. I've confirmed that the ownership settings are otherwise correct (Limited), they are all affiliated with the party, and every other mechanism for hiding health seems to be working (like token permissions to show health). Downgrading to 1.8.0 (above all tested on 1.9.0) fixed the issue. Tested with all other modules disabled.

Edit: Also, they only have Limited ownership of the party token.

**Comment by reonZ** [comment]
it now also take into account the party token, an even when limited, players can see other actors' hp in it

**Comment by ConnorJBeck** [comment]
If my players have limited ownership over the Party token, they are not able to see each other's health. Here is a screenshot from a Player's perspective with Limited Ownership of the Party Token and "Party Alliance as Observed" disabled. The current player is Bunk, he has a animal companion, Tato, but he can still see Malak's health in the combat tracker despite not being able to see it in the Party window.
![image](https://github.com/user-attachments/assets/b23fde02-4e3d-4f10-a66d-9e0707b194c2)

**Comment by reonZ** [comment]
Ok i see, there is a setting for that actually

![image](https://github.com/user-attachments/assets/e6c7af48-956c-4b8f-bfe5-eedca2091e73)

**Comment by reonZ** [comment]
fixed in `1.10.1`

**Comment by p-becker** [comment]
> Ok i see, there is a setting for that actually
> 
> ![image](https://github.com/user-attachments/assets/e6c7af48-956c-4b8f-bfe5-eedca2091e73)

If anyone is searching for these options, they are under p (open party sheet -->click on the "unrestricted" eye in the top right.
