### ISSUE TITLE
"Auto-Set Actor" being set to "On Token Selection" prevents token HUD from loading, even if persistent HUD disabled

### ISSUE THREAD

**Issue by ConnorJBeck** [reonZ/pf2e-hud#29]
Hello, not 100% sure if it's a bug but if it is it's fairly minor. Basically, if you have the persistent token HUD disabled, but Auto-Set Actor is set to "On Token Selection", the Token HUD will not show up. Setting it to None or "Current Combatant" will allow Token HUD to show up. Issue seen on 1.9.0, but tested and confirmed issue is not present in 1.8.0. Tested with all other modules disabled.

**Comment by reonZ** [comment]
It is a bug
