### ISSUE TITLE
[Feature Request] Be able to move the HUD on the screen

### ISSUE THREAD

**Issue by captnobody61** [reonZ/pf2e-hud#3]
I use two screens with foundry pulled across both of them. Having the HUD on my left screen makes it hard to use. Would be nice to be able to move it.

Thanks and loving the HUD btw.

**Comment by reonZ** [comment]
No can do, there are way too many intricate parts between the persistent HUD and the foundry UI elements that requires it to be static.

**Comment by captnobody61** [comment]
Oh well. Looks like popout is working well now so I'll go with that and
have it on a single screen. Thanks for the reply :)
