### ISSUE TITLE
Toggle Targeting in mini-combat tracker never highlights for players

### ISSUE THREAD

**Issue by farling42** [reonZ/pf2e-hud#30]
The "targeting" icon in the mini-combat tracker doesn't match the colouring of the targeting icon in the main Encounter tab.
It never highlights to show which enemy are targeted.

It shows correctly for the GM, but it doesn't work for players trying to target NPCs (it does work for targeting the player's token).

Clicking the icon as a player does toggle the targeting on the canvas (so that part works).

**Comment by reonZ** [comment]
It looks to be working fine for me

![image](https://github.com/user-attachments/assets/84ebdd1b-672b-4dba-a111-b8c964ba424e)
This is from the gm's perspective

![image](https://github.com/user-attachments/assets/5f01d7a3-19f9-47c0-8c60-4345cd3465fb)
And this one from the player's perspective

**Comment by farling42** [comment]
It definitely wasn't working before.

But I've just started up my V12 server again, and it is working exactly as expected.

So I don't know what got it into that state. (My GM login is via chrome, my player login is via Firefox - but both are working properly now.)

**Comment by reonZ** [comment]
I got some issue also when i tried to change the color of my player without reloading the page for both users, when i tested they both originally had the same pink color.
