### ISSUE TITLE
[Feature Request] Light Mode

### ISSUE THREAD

**Issue by EgresMC** [reonZ/pf2e-hud#31]
The Token Tooltip module allowed to have a black text on clear background, that helped one of my players who has a visual impairment.

The PF2E HUD is a great module, and It would be great if there was a way to make it more accessible in such cases.

Thanks for your time.

**Comment by reonZ** [comment]
I don't do theming on my modules, you should turn to a theme module instead. I am not a designer, pulling a single theme/design is already hard enough and a lot of work for me.

And i make extra steps to facilitate the styling of the modules to make it easier for others.
