### ISSUE TITLE
[Suggestion] Posibility to add Conservation of energy to HUD hotbar

### ISSUE THREAD

**Issue by JornieNonsubia** [reonZ/pf2e-hud#33]
It would be great to be able to add CoE as toggle button to hotbar, changing its Icon depends on the current state. 
Maybe some effects on token if it possible or some other indicator of current state except button.
![image](https://github.com/user-attachments/assets/2cbf1bef-7a47-4dc1-8355-ed4accbb3d58)

**Comment by reonZ** [comment]
How would you represent a dropdown as a single action shortcut ? There is a reason the system doesn't do it, because it doesn't make sense.

Also, can you imagine if people asked me to customize every single roll option that can exist like this one ?
