### ISSUE TITLE
[Suggestion] Font size setting for pop-up windows

### ISSUE THREAD

**Issue by PlasticMohawk** [reonZ/pf2e-hud#34]
As a PF2E HUD user, I want to have greater control over pop-up window font size through a setting, similar to other elements of the module, so that I can read it a bit better.

It seems that most elements of the module such as the token HUD, persistent HUD, etc. have such a setting, but there doesn't seem to be one for the pop-up windows.

Below is a screenshot where the left window has a font resized through a setting - but there's no way to resize the right window to match.

Thanks in advance for considering.

![image](https://github.com/user-attachments/assets/62261df3-ccc6-4a53-bedf-ac2de7f12046)

**Comment by reonZ** [comment]
The `Font Size` setting for the popup has been added to version `1.12.0`
