### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by RooskyRex** [reonZ/pf2e-hud#37]
Hi there, 

I absolutely love the concept of this module, however I am having an issue that is showing up on multiple different computers. The hotbar is obscuring the a significant part of the persistent hud. I have tried to fix this through various other modules such as the Custom Hotbar module but it seems the hotbar is tied to the hud. 

I also have the issue that the token hud cannot be used on its explode setting, otherwise all of the information falls outside of the background and is difficult to read. The left and right settings work better but there are still some minor issues with them. I've included screenshots below. This has happened regardless of if UI modules were being used and happened on a MacBook with a relatively small screen and a ultra-wide monitor on a desktop. Thank you for putting this together! Really hopeful to get it working as me and my players really love the idea being represented here.

![image](https://github.com/user-attachments/assets/9b37b04e-e7af-48b1-abec-5aa19a28e3fe)
![image](https://github.com/user-attachments/assets/c6326f7a-d407-44dc-8573-c0a67ab9c63e)
![image](https://github.com/user-attachments/assets/d2fa535c-38df-4089-aab9-a95fef09e39f)
![image](https://github.com/user-attachments/assets/376c8214-672e-49c4-801e-fa5dfe4d13a3)

**Comment by reonZ** [comment]
I would like to see what it looks like with no other modules enabled because those screenshot looks nothing like what it should, just the font being different will already mess up with the layout, that hotbar is not the default one either.

**Comment by RooskyRex** [comment]
Hi there, 

So I did what you suggested and it was working as intended. I spent some time going through modules and determined that  Arius Planeswalker's Stylish Journal for Monk's Enhanced Journal was the culprit.

Sorry for the false alarm and thank you for the help!
