### ISSUE TITLE
Cannot be enabled due to issues in required dependencies

### ISSUE THREAD

**Issue by Crystalwarrior** [reonZ/pf2e-hud#39]
Full screencap of my installed modules here:
![image](https://github.com/user-attachments/assets/495a2498-b2a7-4de1-9040-a8be3e228cf0)

**Comment by reonZ** [comment]
You need to install the dependency (libwrapper), foundry should have offered you to do so on install.

**Comment by Crystalwarrior** [comment]
oh, it didn't install it for some reason even though it said it will. Must be on Foundry end
