### ISSUE TITLE
[Feature Request] Button hide Hud

### ISSUE THREAD

**Issue by altair984** [reonZ/pf2e-hud#41]
Hi,
would it be possible to add a button to hide the whole hud? 

There are times when you have to show a landscape and you don't want to show the hud because it covers part of the screen and can hide important things.

**Comment by reonZ** [comment]
If you want to hide everything, you can use css pretty easily with a macro.

**Comment by altair984** [comment]
I'm sorry but I don't think I have explained myself correctly. I mean a button in the hud that closes the hud to everyone, you being the master, so you can show your players a clean scene in detail. With a css I can only hide my screen, not the screen of all my players, being me the GM.

**Comment by reonZ** [comment]
Considering each player decide what HUD they use if any, it wouldn't make much sense to have something like that from the GM side. The Module doesn't take that much more space than what foundry does already. I can see it being a feature to hide the whole interface (not just the HUD) but this is not something i will implement in this module.
