### ISSUE TITLE
[Feature Request] Typing + or - into the persistent HUD adds or subtracts the number from the current health.

### ISSUE THREAD

**Issue by TheNittles** [reonZ/pf2e-hud#42]
Just wondering if there's a way the Persistent Hud's HP and THP fields could be made to mimic the behavior of the token's fields, where typing in "-3" subtracts 3 HP instead of attempting to set the HP value to negative 3.

**Comment by reonZ** [comment]
Sadly, there is no way for number fields to accept a value such as `+10`

- if i keep them as a number fields, a `+10` will be seen as a regular `10` and therefore won't allow for `add` support
- if i change them to text fields then i lose the possibility of using the mouse wheel and clamping

So, considering i personally like the mouse wheel feature, i won't make the change.
