### ISSUE TITLE
[Feature Request] Turn Timer on Combat Tracker

### ISSUE THREAD

**Issue by FolkvangrForgent** [reonZ/pf2e-hud#43]
I think it would be helpful if there was a timer on the Combat Tracker. This would allow the GM and Players to notice how much time is being spent on their turn.

Ideally the timer would count down from a configurable number of seconds, displaying negative seconds of the time limit is reached. An implementation that just has the timer count up would also be useful.

Currently Modules like `Hurry Up! Combat Timer` provide functionality similar to what I have described but I think a timer integrated into the tracker would be cleaner. If a turn timer is beyond the scope of this module feel free to close this as not planned.

**Comment by reonZ** [comment]
I am not planning to implement such feature.
