### ISSUE TITLE
[Suggestion] Any chance for a DnD5e conversion?

### ISSUE THREAD

**Issue by Drag0nF** [reonZ/pf2e-hud#45]
I know the chances are very slim, but I figure it's worth an ask if we could ever get a version of this for DnD5e, the HUD looks amazing and I would kill to have this for DnD5e! It looks absolutely perfect, having everything I want. I have to smash together like 5 or 6 modules to get the features of this one module, and those don't look anywhere near as nice as this. I fully expect the answer to be no, and that would be more than fair enough but I figure if you don't ask you don't get. Would be happy to contribute a donation if you undertake this task

**Comment by reonZ** [comment]
This module is 100% tailor made to work with pf2e and pf2e alone, it wasn't made to be customizable or system agnostic to begin with, everything is though from the pf2e system perspective and not foundry's. Also i don't play dnd5e and have no interest in spending months of works for a system i don't play.

So no, sorry.

**Comment by NuptupTDOW** [comment]
> I know the chances are very slim, but I figure it's worth an ask if we could ever get a version of this for DnD5e, the HUD looks amazing and I would kill to have this for DnD5e! It looks absolutely perfect, having everything I want. I have to smash together like 5 or 6 modules to get the features of this one module, and those don't look anywhere near as nice as this. I fully expect the answer to be no, and that would be more than fair enough but I figure if you don't ask you don't get. Would be happy to contribute a donation if you undertake this task

For what it's worth, the ARGON HUD module might be what you're looking for with 5e in mind.
