### ISSUE TITLE
Feature Request: Add feats button

### ISSUE THREAD

**Issue by simondw2000** [reonZ/pf2e-hud#46]
Hey, I just started trying out PF2e HUD and absolutely love it.
I'm considering moving to it from Token Action HUD.

There's one thing that TAH does that I don't think you have included yet though, and that's a Feats section like this:
![image](https://github.com/user-attachments/assets/ad6b5010-69ad-4d30-bf57-27125dc46ab0)

Would it be possible to add a feats button inside the Actions/Inventory/Spells/Skills/Extras section that opens up a list of the character's feats?

**Comment by reonZ** [comment]
This isn't in the scope of the module, the different menus are there so you can "play" the actor: make rolls mostly.

Feats are 100% just information and most of the time, they have a related action which can be found in the actions menu.

Also, and to be honest, that one is a big deal, the layouts are set in stone by now, adding an extra icon would mess up with it all.

**Comment by simondw2000** [comment]
Shame. But fair enough. Thanks for the explanation.
