### ISSUE TITLE
Huge performance loss when used alongside Dorako UI

### ISSUE THREAD

**Issue by ThePhxRises** [reonZ/pf2e-hud#48]
[Issue also filed with dorako ui](https://github.com/Dorako/pf2e-dorako-ui/issues/345)

Setting up a new campaign and as I was going through and enabling my usual set of modules, I noticed that having pf2e-doraki-ui enabled with a theme applied alongside the Persistent HUD from pf2e-hud causes a massive performance loss. On my system I go from a steady 165 (my refresh rate) to somewhere between 50 and 80. Disabling either module or the theme/persistent HUD in settings resolves the performance loss.

On further analysis it seems this performance loss also happens with the Persistent HUD disabled when either of the Token HUDs are drawn, seeming like it occurs with any UI drawn by pf2e-hud

I would have assumed these two modules worked together given Dorako UI has a setting specifically for theming the HUD, but it would seem not. Is this a new issue?

I was going to try and add pf2e-hud to the Excluded Applications list but I can't figure out which identifier from the logs to use for it.

**Comment by reonZ** [comment]
I am not sure why you would come here to make a report and not go to dorako instead if you say that disabling the theme resolves the issues, it means that dorako is the problem, not this module.

I have no control about what he does with his module or how he interacts with this one.
