### ISSUE TITLE
Can't enable module on foundryvtt

### ISSUE THREAD

**Issue by hakimassouane2** [reonZ/pf2e-hud#49]
Hello !

When I try to activate the module from the module menu on Foundry it asks me if I want to restart the world, to which I answer yes, it restarts the world, but then to my surprise the module still stays in the non activated modules and nothing happens. I tried taking a look at the console but nothing seems to pop up from there, any idea ?

**Comment by reonZ** [comment]
do you have libwrapper enabled as well ? also this is more of a foundry question than a module specific one, you would have more chance of getting support for it on the foundry discord.
