### ISSUE TITLE
[Feature Request] Add the possibility to disable the Agile trait on skill actions with the Attack trait

### ISSUE THREAD

**Issue by Fraxinus1753** [reonZ/pf2e-hud#51]
It would be nice to have the possibility to disable by default the Agile trait on skill actions with the Attack trait, such as Trip or Shove. If a character uses a non-Agile weapon to perform those manoeuvers, they must right-click the action shortcut to untick Agile for every roll with MAP, which is a bit cumbersome. In addition, this prevents creating shortcuts with MAP in the persistend HUD, as those are Agile by default and cannot be changed once in the HUD.

**Comment by reonZ** [comment]
You can now create skill action shortcuts with variants from the variants popup.

**Comment by Fraxinus1753** [comment]
Just saw that, it's great, thanks a ton for the quick update!
