### ISSUE TITLE
[Feature request] Add the possibility to push GM-created shortcuts to all clients owning the actor

### ISSUE THREAD

**Issue by Fraxinus1753** [reonZ/pf2e-hud#52]
Absolutely great module! It would be nice if it were possible for the GM to create shortcuts for an actor and to push them to all clients owning the actor. This would enable every player to have access to the same set of shortcuts for every character (especially useful when players often play other people's character in case one player can't make it), and allows the GM to set up players' shortcuts ahead of time without logging into their sessions (as players may not have the time or know-how to create the shortcuts themselves if sessions are short).

**Comment by reonZ** [comment]
i have not plan on implementing something like that but it is entirely possible with a bit of javasript.

**Comment by reonZ** [comment]
i have no plans on implementing something like that but it is entirely possible with a bit of javasript.
