### ISSUE TITLE
[Feature request] Encounter tracker customisation

### ISSUE THREAD

**Issue by ghost** [reonZ/pf2e-hud#54]
Hi

I was hoping some additional customisation options could be added to the 'Encounter tracker'. 

First that would be helpful is being able to reposition (and remember) the location of the tracker as currently it sits over one of the two anchor points of 'Global Progress Clocks' and can't be repositioned as far as I can tell. 

![Capture](https://github.com/user-attachments/assets/31cc55bc-3d85-4222-b3db-7696fc97fde6)

The other issue I'm having is with the black text for hostile NPC names - it is difficult to read with most themes. This seems to be with or without dark mode, PF2E Dorako UI enabled/disabled, etc. Could there be an additional customisation for this or an option to make it the same color?

Thank you

**Comment by reonZ** [comment]
The tracker isn't gonna move, there are reason for that that i don't feel like going into.

I will slightly increase the border shadow but that won't change much, an option for that is overkill though, you can easily change it yourself using some custom css, especially if you are using dorako.
