### ISSUE TITLE
Request: Token pop up recall knowledge should show recall knowledge type in parenthesis

### ISSUE THREAD

**Issue by weihanderz** [reonZ/pf2e-hud#58]
![image](https://github.com/user-attachments/assets/4b3b1a16-48be-460e-b79d-100235e03456)
It would be nice if GMs could hover over the recall knowledge DC and see the type of recall knowledge based on the creature type. This way GMs can know which type of knowledge check roll to request without having to open the character sheet.

**Comment by reonZ** [comment]
Could be, though not that useful because when a player uses the custom recall knowledge from the extras sidebar while targeting the NPC, all the related DCs are shown to the GM.

**Comment by reonZ** [comment]
not sure what your screenshot means, the RK DCs are on the NPC already and as i shown you, they are in the RK message

**Comment by weihanderz** [comment]
Ah, sorry I didn't make things clearer. It was just a suggestion for DMs to be able to quickly see the RK type without having to open another window. Mockup included.
![image](https://github.com/user-attachments/assets/ddb4d3d7-1e05-44fb-ab09-9664d1aec0c8)
