### ISSUE TITLE
Persistent HUD blocked by other UI elements

### ISSUE THREAD

**Issue by mgoldstein322** [reonZ/pf2e-hud#6]
Hello, this is less an issue and more of a request for a change. I'm using the Taskbar module, and I would like to be able to move the persistent HUD up (either manually or with a setting) so that the taskbar is no longer in front of it. I can obviously unlock the taskbar so that it auto-hides, but I prefer to have it locked unhidden. Additionally, because of the way this module interacts with the hotbar, it breaks the rendering of the hot bar when both persistent HUD is enabled and the hotbar is docked in the taskbar.

I know this isn't a module that your wrote or anything, but it would be really nice if these two played nice together :)

Edit: after some other playing around, this also affects the combat tracker.

**Comment by reonZ** [comment]
sorry, but when i started this module, the first directive i gave myself was that i would not support any other module, because request like that would never end and make the development and maintenance of the module a nightmare.

**Comment by mgoldstein322** [comment]
Fair enough. I think even the ability to click and drag the persistent HUD and combat tracker elements around would be beneficial for general usability and not relate to any specific module support, though.
