### ISSUE TITLE
Dice Panel HUD misinterprets 10 of the same dice already in chat

### ISSUE THREAD

**Issue by Cerapter** [reonZ/pf2e-hud#60]
When using Shift+click to add dice to the current chat message, the Dice Panel correctly increases the dice count assuming the same type of dice is added up until 10dX: `/r 1d20` becomes `/r 2d20`, and so on.

However, if, using this same method, the user would add 11 dice, `/r 10d20` becomes `/r 110d20`. Adding more dice with Shift+click seems to double the ones in the count, `/r 110d20` becoming `/r 11110d20`, then `/r 111111110d20`, and so on.

**Comment by reonZ** [comment]
I will revisit the thing later, this was scrapped from an old module of mine and i just put it as is
