### ISSUE TITLE
[Request] Add Effect: Aid to Aid chat message

### ISSUE THREAD

**Issue by tnarv** [reonZ/pf2e-hud#62]
It would be nice if the Aid check posted the effect alongside the result when rolling an Aid check. It's just a bit QoL that would allow a user to drag the effect onto the token they are aiding. Currently, it seems the best way is to post the whole description of the ability which takes up quite a lot of chat space. 

It'd look something like this:
![image](https://github.com/user-attachments/assets/0b90648e-6465-4e59-a08d-24791c0eb8b2)

**Comment by reonZ** [comment]
You gonna have to go ask the system devs for it then, this isn't mine..
