### ISSUE TITLE
Request: Allow the Top-Right Calendar Display to Use Simple Calendar

### ISSUE THREAD

**Issue by Armandeus66** [reonZ/pf2e-hud#64]
If the time is displayed using this module in the top-right corner, it displays what the PF2E system has as selected, but you cannot select a custom calendar made with Simple Calendar in the PF2E system settings. If you have a homebrew setting you can't really make use of this feature. You can only select from the 4 pre-determined choices in the system.
I would like to request that calendars from Simple Calendar be available to select for the display.
Thanks!

**Comment by reonZ** [comment]
No, i am not supporting any third party module, there would be no end to that kind of request if i were to.
