### ISSUE TITLE
HUD no longer working after update last night.

### ISSUE THREAD

**Issue by weihanderz** [reonZ/pf2e-hud#66]
It may be a coincidence but after updating last night, my pf2e hud no longer works. Persistent, pop up, token huds all do not seem to function, even with all other modules turned off.

**Comment by weihanderz** [comment]
It looks like it was an issue with the new version. Started working again after rollback.

**Comment by reonZ** [comment]
An error would be nice so i can do seomething about it.

**Comment by weihanderz** [comment]
Hmm. Updated again to test but it seems to be working now. Maybe just a fluke.
