### ISSUE TITLE
Time Tracker is shown to players even if access to clock is globally disabled

### ISSUE THREAD

**Issue by Vagor96** [reonZ/pf2e-hud#67]
Players can read the clock via the time tracker even if their access to the clock is disabled via the pathfinder core clock settings.

To reproduce:
- Enable pf2e hud
- Disable player access to clock in the pf2e clock settings
- Log in as player and see time tracker with correct time on the top right

**Comment by reonZ** [comment]
I never thought this could be a thing, there is a way to scramble the date/time though but i will do something about that anyways.

![image](https://github.com/user-attachments/assets/4411e945-e01b-40f2-8907-766a3315780d)
