### ISSUE TITLE
Macro bar stops working when switching between characters

### ISSUE THREAD

**Issue by thejoester** [reonZ/pf2e-hud#69]
Since the 6.8.0 PF2e system update, I am having this issue with PF2e HUD. 

As GM I have my settings to not lock persistent actor. However if I switch characters my hotbar suddenly stops working, I cannot switch bars and the macros on them do nothing. If I refresh it starts working until I change actors.

**Comment by thejoester** [comment]
Update: ran the find the culprit tool, it reported this: 

![image](https://github.com/user-attachments/assets/a0b11473-b423-4abc-82a9-13e8cbc5a0c0)

also tried disabling all macros except PF2e HUD and libwrapper and same issue. 

here is a video if the issue to help clarify. 
[https://youtu.be/X7mZI9-eVAc](https://youtu.be/X7mZI9-eVAc)

**Comment by reonZ** [comment]
This is fixed with update `1.26.1`
