### ISSUE TITLE
Support Suboptions on Tiles

### ISSUE THREAD

**Issue by TehT** [reonZ/pf2e-hud#7]
As an example, the Inventor's Megaton Strike has a Rolloption , but also a suboption dropdown toggle to select stable or unstable, but these are not accessible when placing the feature as a tile.

Rule Element:
`{"key":"RollOption","option":"megaton","suboptions":[{"label":"PF2E.SpecificRule.Inventor.Unstable.Stable","value":"stable"},{"label":"PF2E.TraitUnstable","value":"unstable"}],"toggleable":true,"value":true,"selection":"stable"}`

It would be neat if it was possible to get the suboption on the toggle, or as a separate toggle if that is not possible.

**Comment by reonZ** [comment]
If by "tile" you mean "shortcut", then no, dropdown roll options cannot be turned into shortcuts, there is no way to represent a choice list as a simple button.
