### ISSUE TITLE
[Feature Request] Provide conversions to the Calendar in the HUD for Day/Month names.

### ISSUE THREAD

**Issue by Payden-Pringle** [reonZ/pf2e-hud#70]
This was inspired by https://github.com/reonZ/pf2e-hud/issues/64.

Essentially, it'd be nice if we could define what the Day/Month names are in the settings for the HUD so that they appear correctly for homebrew settings.

Say, if I go to Configure Settings > PF2e HUD > Time Tracker, there might be a "Customize Names" button that I click to open another Modal with a Days & Months menu that has the Golarion names on the left and blank fields on the right and I can just type in the appropriate names which would then appear in the Time Tracker HUD element in place of the originals.

This wouldn't address where there are more/less, but I think it'd go a long way.

**Comment by reonZ** [comment]
I have no interest in re-implementing a calendar system on top of what already exists. Especially since foundry is supposed to add support for calendars with V13.
