### ISSUE TITLE
Assurance not an option in skills

### ISSUE THREAD

**Issue by AKA-Kira** [reonZ/pf2e-hud#72]
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/b044549a-3f67-48dd-bac1-2428b548cc86" />

As seen above when selecting Treat Wounds it is not prompting to use Assurance instead of rolling, could not find where this macro was located that was created into the HUD from the skills options either.

**Comment by reonZ** [comment]
This is not related to this module, this is from the system.

**Comment by AKA-Kira** [comment]
Thanks for confirming!
