### ISSUE TITLE
Module wont activate in settings

### ISSUE THREAD

**Issue by NRschwier** [reonZ/pf2e-hud#8]
Hello! The module wont enable in the manage module settings. I click the check mark and save it but then it reloads and unenables itself everytime.

**Comment by reonZ** [comment]
you probably didn't install its dependency `lib wrapper`

**Comment by NRschwier** [comment]
I do have libwrapper installed and activated as well

**Comment by reonZ** [comment]
only other thing i can think of would be the system version not being the latest.

no matter what it is, this is unlikely a module issue, you better off looking for help with foundry.

**Comment by reonZ** [comment]
closing this for lack of follow up
